### ISSUE TITLE
Git push/pull broken in container

### ISSUE THREAD

**Issue by Jquinny** [UAlbertaFSAE/f1tenth#81]
**Describe the bug**

can't push or pull changes when inside the devcontainer anymore. Not sure what happened but it broke on at least two members computers, so I imagine it is a general issue.

**To Reproduce**

clone repo, open up devcontainer in vscode, try to do a git pull or push when inside the devcontainer terminal.

**Expected behavior**

expect to be able to pull and push git stuff to github from inside devcontainer

**Screenshots**

**Operating System**
 - [x] Windows WSL
- [x] Mac with no VM
- [ ] Mac with VM
- [ ] Linux

**Additional context**

**Comment by fsoehn** [comment]
Fixed it on my machine (Mac M1) by running:
`ssh-add $HOME/.ssh/id_rsa`
on my home terminal to add my SSH key to the SSH Agent dev containers use.

[https://code.visualstudio.com/remote/advancedcontainers/sharing-git-credentials](url)
